### PR TITLE
Use type inference instead of test_value (cont. #34)

### PR DESCRIPTION
**Pull request by cscherrer**
This PR adds a few tests based on suggestions in comments from @johnnychen94 

I'm targeting master with this because @MasonProtter's PR is in not a branch in this repo, but in a separate fork. Let me know if there's another target that works better for you.

### CODE REVIEW

**Comment by cscherrer** [comment]
Oh wait, I didn't add the tests

**Comment by johnnychen94** [comment]
The test failure is quite interesting...

**Comment by johnnychen94** [comment]
@cscherrer thanks for putting this up (and the reminder 😆 )

**Comment by MasonProtter** [comment]
Thanks for doing this @cscherrer! I feel a tiny tiny weight has been lifted off my shoulders. One less PR to think "I should really get around to fixing that"

**Comment by cscherrer** [comment]
Thanks @johnnychen94 and @MasonProtter, 
I feel like my part in this was very small, but I'm happy to see it moving forward!

**Comment by timholy** [comment]
On every Julia version I've tested (1.0, 1.6, and 1.9), the following generates an error:
```julia
julia> using MappedArrays
[ Info: Precompiling MappedArrays [dbb5928d-eab1-5f90-85c2-b9b0edb7c900]

julia> _zero(x) = x > 0 ? x : 0
_zero (generic function with 1 method)

julia> _sum(x, y) = _zero(x) + _zero(y)
_sum (generic function with 1 method)

julia> map(_sum, [1, 1.0], [1.0, missing])
ERROR: TypeError: non-boolean (Missing) used in boolean context
Stacktrace:
 [1] _zero
   @ ./REPL[2]:1 [inlined]
 [2] _sum
   @ ./REPL[3]:1 [inlined]
 [3] #4
   @ ./generator.jl:36 [inlined]
 [4] iterate
   @ ./generator.jl:47 [inlined]
 [5] collect_to!(dest::Vector{Float64}, itr::Base.Generator{Base.Iterators.Zip{Tuple{Vector{Float64}, Vector{Union{Missing, Float64}}}}, Base.var"#4#5"{typeof(_sum)}}, offs::Int64, st::Tuple{Int64, Int64})
   @ Base ./array.jl:728
 [6] collect_to_with_first!(dest::Vector{Float64}, v1::Float64, itr::Base.Generator{Base.Iterators.Zip{Tuple{Vector{Float64}, Vector{Union{Missing, Float64}}}}, Base.var"#4#5"{typeof(_sum)}}, st::Tuple{Int64, Int64})
   @ Base ./array.jl:706
 [7] collect(itr::Base.Generator{Base.Iterators.Zip{Tuple{Vector{Float64}, Vector{Union{Missing, Float64}}}}, Base.var"#4#5"{typeof(_sum)}})
   @ Base ./array.jl:687
 [8] map(::Function, ::Vector{Float64}, ::Vector{Union{Missing, Float64}})
   @ Base ./abstractarray.jl:2383
 [9] top-level scope
   @ REPL[4]:1
```
yet on versions before 1.9,
```julia
julia> eltype(mappedarray(_sum, [1, 1.0], [1.0, missing]))
Union{Missing, Float64, Int64}
```
This appears to be a test that *should* fail but happened not to at the time at which it was written. I'm going to take the liberty of changing this by making `_zero` robust against `::Missing` arguments.

**Pull request merged**
